language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
git:
  depth: 3
# command to run tests
script:
  - py.test --cov=./md5checker
after_success:
  - codecov
