language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
before-install:
  - pip install pytest pytest-cov
git:
  depth: 3
# command to run tests
script: "py.test --cov=./"
